version: "3.8"

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
